In [1]:
from titulospub import *
from titulospub.core.ntnb.vna_ntnb import calculo_vna_ajustado_ntnb
import pandas as pd

In [2]:
var = VariaveisMercado()
var.atualizar_tudo()

Atualizando variáveis de mercado...
Buscando feriados via scraping...
Calculando IPCA dict...
Buscando CDI...
Realizando scraping ANBIMA...
[OK] Cache salvo para todos os títulos ANBIMA.
Realizando scraping BMF...
[INFO] Encontrados 4 arquivos com prefixo Interest_Rate_SettlementPriceFile_Futures_20260220_
[INFO] Arquivo mais recente selecionado: Interest_Rate_SettlementPriceFile_Futures_20260220_4.csv
[INFO] Data de modificação: Fri Feb 20 19:04:00 2026
[OK] Cache salvo para todos os contrados de DI e DAP.
Realizando scraping VNA_LFT...
[OK] Cache salvo para VNA_LFT.
[OK] Atualização concluída.

In [ ]:
var._ipca_dict

{'ULTIMO_MES_IPCA': 1,
 'INDICE_IPCA_DATA_BASE': 1614.62,
 'INDICE_IPCA_FECHADO_ATUAL': 7427.72,
 'INDICE_IPCA_FECHADO_ANTERIOR': 7403.29,
 'VAR_IPCA_ATUAL': 0.33,
 'VAR_IPCA_ANTERIOR': 0.33,
 'IPCA_PROJ': 0.45,
 'IPCA_USADO': 0.45}

:

In [3]:
calculo_vna_ajustado_ntnb(data=pd.Timestamp("2026-02-20"), data_liquidacao=pd.Timestamp("2026-02-23"), ipca_dict=None, feriados=None, leilao=False)

4603.733616

In [4]:
dados = AnbimaClient().fetch_for_dates(MERCADO_SECUNDARIO_TPF, ["2026-01-21", "2026-01-20", "2026-01-19", "2026-01-18"])
dados

[[{'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2026-03-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0251,
   'taxa_venda': 0.0182,
   'taxa_indicativa': 0.0213,
   'intervalo_min_d0': -0.0503,
   'intervalo_max_d0': 0.0674,
   'intervalo_min_d1': -0.0511,
   'intervalo_max_d1': 0.0676,
   'pu': 18215.384108,
   'desvio_padrao': 0.00080151510279,
   'codigo_isin': 'BRSTNCLF1RE0'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2026-04-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2024-01-05',
   'taxa_compra': 14.7607,
   'taxa_venda': 14.7465,
   'taxa_indicativa': 14.7572,
   'intervalo_min_d0': 14.6982,
   'intervalo_max_d0': 14.9442,
   'intervalo_min_d1': 14.712,
   'intervalo_max_d1': 14.9553,
   'pu': 973.590039,
   'desvio_padrao': 0.00224891640352,
   'codigo_isin': 'BRSTNCLTN8B5'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2026-07-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2023-01-06',
   'taxa_compra': 14.4529,
   'taxa_venda': 14.4409,
   'taxa_indicativa': 14.4474,
   'intervalo_min_d0': 14.3109,
   'intervalo_max_d0': 14.673,
   'intervalo_min_d1': 14.3299,
   'intervalo_max_d1': 14.6873,
   'pu': 942.796683,
   'desvio_padrao': 0.00331380320176,
   'codigo_isin': 'BRSTNCLTN848'},
  {'tipo_titulo': 'NTN-B',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2026-08-15',
   'data_referencia': '2026-01-20',
   'codigo_selic': '760199',
   'data_base': '2000-07-15',
   'taxa_compra': 10.3441,
   'taxa_venda': 10.3117,
   'taxa_indicativa': 10.33,
   'intervalo_min_d0': 9.9204,
   'intervalo_max_d0': 10.7749,
   'intervalo_min_d1': 9.9403,
   'intervalo_max_d1': 10.7997,
   'pu': 4601.380001,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCNTB4U6'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2026-09-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': -0.01,
   'taxa_venda': -0.0188,
   'taxa_indicativa': -0.0157,
   'intervalo_min_d0': -0.0419,
   'intervalo_max_d0': 0.0572,
   'intervalo_min_d1': -0.0419,
   'intervalo_max_d1': 0.0573,
   'pu': 18217.533573,
   'desvio_padrao': 0.00056242645741,
   'codigo_isin': 'BRSTNCLF1RF7'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2026-10-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2024-07-05',
   'taxa_compra': 14.0601,
   'taxa_venda': 14.0424,
   'taxa_indicativa': 14.0478,
   'intervalo_min_d0': 13.782,
   'intervalo_max_d0': 14.3662,
   'intervalo_min_d1': 13.8151,
   'intervalo_max_d1': 14.3961,
   'pu': 912.759393,
   'desvio_padrao': 0.00217944946948,
   'codigo_isin': 'BRSTNCLTN8G4'},
  {'tipo_titulo': 'NTN-F',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2027-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '950199',
   'data_base': '2016-01-15',
   'taxa_compra': 13.6959,
   'taxa_venda': 13.6597,
   'taxa_indicativa': 13.6773,
   'intervalo_min_d0': 13.3039,
   'intervalo_max_d0': 14.0278,
   'intervalo_min_d1': 13.3418,
   'intervalo_max_d1': 14.0642,
   'pu': 975.839101,
   'desvio_padrao': 0.00191850636173,
   'codigo_isin': 'BRSTNCNTF1P8'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2027-03-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0218,
   'taxa_venda': 0.0208,
   'taxa_indicativa': 0.0215,
   'intervalo_min_d0': -0.0143,
   'intervalo_max_d0': 0.0394,
   'intervalo_min_d1': -0.0141,
   'intervalo_max_d1': 0.0395,
   'pu': 18211.522358,
   'desvio_padrao': 0.00022622214746,
   'codigo_isin': 'BRSTNCLF1RG5'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2027-04-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2025-01-10',
   'taxa_compra': 13.5117,
   'taxa_venda': 13.4992,
   'taxa_indicativa': 13.5042,
   'intervalo_min_d0': 13.0602,
   'intervalo_max_d0': 13.8409,
   'intervalo_min_d1': 13.0992,
   'intervalo_max_d1': 13.8795,
   'pu': 861.319954,
   'desvio_padrao': 0.00122754109504,
   'codigo_isin': 'BRSTNCLTN8I0'},
  {'tipo_titulo': 'NTN-B',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2027-05-15',
   'data_referencia': '2026-01-20',
   'codigo_selic': '760199',
   'data_base': '2000-07-15',
   'taxa_compra': 8.6342,
   'taxa_venda': 8.6078,
   'taxa_indicativa': 8.62,
   'intervalo_min_d0': 8.2896,
   'intervalo_max_d0': 8.8509,
   'intervalo_min_d1': 8.3199,
   'intervalo_max_d1': 8.8808,
   'pu': 4500.103822,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCNTB682'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2027-07-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2023-07-07',
   'taxa_compra': 13.3624,
   'taxa_venda': 13.3476,
   'taxa_indicativa': 13.3547,
   'intervalo_min_d0': 12.8689,
   'intervalo_max_d0': 13.7198,
   'intervalo_min_d1': 12.914,
   'intervalo_max_d1': 13.7639,
   'pu': 836.044203,
   'desvio_padrao': 0.0021740241351,
   'codigo_isin': 'BRSTNCLTN871'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2027-09-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0323,
   'taxa_venda': 0.0299,
   'taxa_indicativa': 0.0317,
   'intervalo_min_d0': -0.0002,
   'intervalo_max_d0': 0.0505,
   'intervalo_min_d1': -0.0001,
   'intervalo_max_d1': 0.0504,
   'pu': 18206.549444,
   'desvio_padrao': 0.00044002839681,
   'codigo_isin': 'BRSTNCLF1RH3'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2027-10-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2025-07-04',
   'taxa_compra': 13.2881,
   'taxa_venda': 13.279,
   'taxa_indicativa': 13.282,
   'intervalo_min_d0': 12.7734,
   'intervalo_max_d0': 13.6918,
   'intervalo_min_d1': 12.8206,
   'intervalo_max_d1': 13.738,
   'pu': 810.321195,
   'desvio_padrao': 0.00085911402619,
   'codigo_isin': 'BRSTNCLTN8L4'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2028-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2024-01-05',
   'taxa_compra': 13.1991,
   'taxa_venda': 13.1647,
   'taxa_indicativa': 13.179,
   'intervalo_min_d0': 12.6468,
   'intervalo_max_d0': 13.6123,
   'intervalo_min_d1': 12.7081,
   'intervalo_max_d1': 13.673,
   'pu': 786.831974,
   'desvio_padrao': 0.00505311372621,
   'codigo_isin': 'BRSTNCLTN897'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2028-03-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0458,
   'taxa_venda': 0.0432,
   'taxa_indicativa': 0.0445,
   'intervalo_min_d0': 0.0243,
   'intervalo_max_d0': 0.0542,
   'intervalo_min_d1': 0.0241,
   'intervalo_max_d1': 0.0543,
   'pu': 18198.825943,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCLF1RI1'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2028-04-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2026-01-09',
   'taxa_compra': 13.2158,
   'taxa_venda': 13.1923,
   'taxa_indicativa': 13.1988,
   'intervalo_min_d0': 12.657,
   'intervalo_max_d0': 13.6612,
   'intervalo_min_d1': 12.7193,
   'intervalo_max_d1': 13.7229,
   'pu': 762.560712,
   'desvio_padrao': 0.00141405814237,
   'codigo_isin': 'BRSTNCLTN8M2'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2028-07-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2024-07-05',
   'taxa_compra': 13.2229,
   'taxa_venda': 13.1973,
   'taxa_indicativa': 13.21,
   'intervalo_min_d0': 12.6547,
   'intervalo_max_d0': 13.6856,
   'intervalo_min_d1': 12.7222,
   'intervalo_max_d1': 13.7529,
   'pu': 739.838517,
   'desvio_padrao': 0.00100815720004,
   'codigo_isin': 'BRSTNCLTN8F6'},
  {'tipo_titulo': 'NTN-B',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2028-08-15',
   'data_referencia': '2026-01-20',
   'codigo_selic': '760199',
   'data_base': '2000-07-15',
   'taxa_compra': 8.174,
   'taxa_venda': 8.1457,
   'taxa_indicativa': 8.1612,
   'intervalo_min_d0': 7.803,
   'intervalo_max_d0': 8.4825,
   'intervalo_min_d1': 7.8141,
   'intervalo_max_d1': 8.4935,
   'pu': 4491.020757,
   'desvio_padrao': 0.00209767345171,
   'codigo_isin': 'BRSTNCNTB4X0'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2028-09-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0524,
   'taxa_venda': 0.0517,
   'taxa_indicativa': 0.052,
   'intervalo_min_d0': 0.0428,
   'intervalo_max_d0': 0.0628,
   'intervalo_min_d1': 0.0428,
   'intervalo_max_d1': 0.0625,
   'pu': 18191.15709,
   'desvio_padrao': 5.878664814e-05,
   'codigo_isin': 'BRSTNCLF1RK7'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2029-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2022-02-11',
   'taxa_compra': 13.32,
   'taxa_venda': 13.3086,
   'taxa_indicativa': 13.315,
   'intervalo_min_d0': 12.7568,
   'intervalo_max_d0': 13.7977,
   'intervalo_min_d1': 12.8244,
   'intervalo_max_d1': 13.8653,
   'pu': 694.13879,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCLTN806'},
  {'tipo_titulo': 'NTN-F',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2029-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '950199',
   'data_base': '2018-01-05',
   'taxa_compra': 13.3607,
   'taxa_venda': 13.3277,
   'taxa_indicativa': 13.3462,
   'intervalo_min_d0': 12.7955,
   'intervalo_max_d0': 13.8192,
   'intervalo_min_d1': 12.8649,
   'intervalo_max_d1': 13.8885,
   'pu': 932.140108,
   'desvio_padrao': 0.00306295841957,
   'codigo_isin': 'BRSTNCNTF1Q6'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2029-03-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0609,
   'taxa_venda': 0.0592,
   'taxa_indicativa': 0.0599,
   'intervalo_min_d0': 0.0491,
   'intervalo_max_d0': 0.0815,
   'intervalo_min_d1': 0.0491,
   'intervalo_max_d1': 0.081,
   'pu': 18182.231346,
   'desvio_padrao': 4.522665143e-05,
   'codigo_isin': 'BRSTNCLF1RL5'},
  {'tipo_titulo': 'NTN-B',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2029-05-15',
   'data_referencia': '2026-01-20',
   'codigo_selic': '760199',
   'data_base': '2000-07-15',
   'taxa_compra': 8.0654,
   'taxa_venda': 8.0332,
   'taxa_indicativa': 8.0506,
   'intervalo_min_d0': 7.6856,
   'intervalo_max_d0': 8.3319,
   'intervalo_min_d1': 7.706,
   'intervalo_max_d1': 8.3528,
   'pu': 4386.271911,
   'desvio_padrao': 0.00152616075824,
   'codigo_isin': 'BRSTNCNTB716'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2029-07-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2025-07-04',
   'taxa_compra': 13.4556,
   'taxa_venda': 13.4457,
   'taxa_indicativa': 13.45,
   'intervalo_min_d0': 12.8985,
   'intervalo_max_d0': 13.9312,
   'intervalo_min_d1': 12.9694,
   'intervalo_max_d1': 14.0022,
   'pu': 650.08294,
   'desvio_padrao': 0.00066154164646,
   'codigo_isin': 'BRSTNCLTN8K6'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2029-09-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0747,
   'taxa_venda': 0.0726,
   'taxa_indicativa': 0.0739,
   'intervalo_min_d0': 0.0616,
   'intervalo_max_d0': 0.0923,
   'intervalo_min_d1': 0.0616,
   'intervalo_max_d1': 0.0917,
   'pu': 18167.531193,
   'desvio_padrao': 3.518636099e-05,
   'codigo_isin': 'BRSTNCLF1RM3'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2030-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2024-01-05',
   'taxa_compra': 13.5518,
   'taxa_venda': 13.5405,
   'taxa_indicativa': 13.5441,
   'intervalo_min_d0': 13.0058,
   'intervalo_max_d0': 14.0198,
   'intervalo_min_d1': 13.0811,
   'intervalo_max_d1': 14.0953,
   'pu': 608.662538,
   'desvio_padrao': 0.00129530286806,
   'codigo_isin': 'BRSTNCLTN8A7'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2030-03-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0866,
   'taxa_venda': 0.0829,
   'taxa_indicativa': 0.0851,
   'intervalo_min_d0': 0.0696,
   'intervalo_max_d0': 0.1018,
   'intervalo_min_d1': 0.0695,
   'intervalo_max_d1': 0.1014,
   'pu': 18152.758177,
   'desvio_padrao': 0.00014960260693,
   'codigo_isin': 'BRSTNCLF1RO9'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2030-06-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.093,
   'taxa_venda': 0.0899,
   'taxa_indicativa': 0.0921,
   'intervalo_min_d0': 0.0731,
   'intervalo_max_d0': 0.105,
   'intervalo_min_d1': 0.0729,
   'intervalo_max_d1': 0.1048,
   'pu': 18143.468118,
   'desvio_padrao': 0.00047812438758,
   'codigo_isin': 'BRSTNCLF1RQ4'},
  {'tipo_titulo': 'NTN-B',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2030-08-15',
   'data_referencia': '2026-01-20',
   'codigo_selic': '760199',
   'data_base': '2000-07-15',
   'taxa_compra': 7.9908,
   'taxa_venda': 7.9587,
   'taxa_indicativa': 7.9771,
   'intervalo_min_d0': 7.6287,
   'intervalo_max_d0': 8.159,
   'intervalo_min_d1': 7.6657,
   'intervalo_max_d1': 8.1963,
   'pu': 4384.244277,
   'desvio_padrao': 0.00396766867694,
   'codigo_isin': 'BRSTNCNTB3B8'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2030-09-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0975,
   'taxa_venda': 0.0946,
   'taxa_indicativa': 0.0959,
   'intervalo_min_d0': 0.0762,
   'intervalo_max_d0': 0.1086,
   'intervalo_min_d1': 0.0759,
   'intervalo_max_d1': 0.1086,
   'pu': 18136.072501,
   'desvio_padrao': 4.923657177e-05,
   'codigo_isin': 'BRSTNCLF1RR2'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2030-12-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0992,
   'taxa_venda': 0.0955,
   'taxa_indicativa': 0.0973,
   'intervalo_min_d0': 0.0802,
   'intervalo_max_d0': 0.1101,
   'intervalo_min_d1': 0.0803,
   'intervalo_max_d1': 0.11,
   'pu': 18130.516682,
   'desvio_padrao': 0.0002714340804,
   'codigo_isin': 'BRSTNCLF1RT8'},
  {'tipo_titulo': 'NTN-C',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2031-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '770100',
   'data_base': '2000-07-01',
   'taxa_compra': 8.083,
   'taxa_venda': 7.9248,
   'taxa_indicativa': 8.0199,
   'intervalo_min_d0': 7.5261,
   'intervalo_max_d0': 8.4496,
   'intervalo_min_d1': 7.4754,
   'intervalo_max_d1': 8.3978,
   'pu': 7503.573858,
   'desvio_padrao': 0.03736906434057,
   'codigo_isin': 'BRSTNCNTC0K4'},
  {'tipo_titulo': 'NTN-F',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2031-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '950199',
   'data_base': '2020-01-10',
   'taxa_compra': 13.7654,
   'taxa_venda': 13.7534,
   'taxa_indicativa': 13.7585,
   'intervalo_min_d0': 13.2338,
   'intervalo_max_d0': 14.2143,
   'intervalo_min_d1': 13.3184,
   'intervalo_max_d1': 14.2987,
   'pu': 882.844411,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCNTF204'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2031-03-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.0994,
   'taxa_venda': 0.0979,
   'taxa_indicativa': 0.0985,
   'intervalo_min_d0': 0.0832,
   'intervalo_max_d0': 0.1117,
   'intervalo_min_d1': 0.0834,
   'intervalo_max_d1': 0.1116,
   'pu': 18125.14302,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCLF1RU6'},
  {'tipo_titulo': 'NTN-B',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2031-05-15',
   'data_referencia': '2026-01-20',
   'codigo_selic': '760199',
   'data_base': '2000-07-15',
   'taxa_compra': 7.9564,
   'taxa_venda': 7.9144,
   'taxa_indicativa': 7.9367,
   'intervalo_min_d0': 7.6051,
   'intervalo_max_d0': 8.1088,
   'intervalo_min_d1': 7.6449,
   'intervalo_max_d1': 8.1487,
   'pu': 4282.261638,
   'desvio_padrao': 0.00369097556752,
   'codigo_isin': 'BRSTNCNTB7X3'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2031-06-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.1007,
   'taxa_venda': 0.099,
   'taxa_indicativa': 0.0999,
   'intervalo_min_d0': 0.0855,
   'intervalo_max_d0': 0.1131,
   'intervalo_min_d1': 0.0853,
   'intervalo_max_d1': 0.1136,
   'pu': 18119.405042,
   'desvio_padrao': 0.00011217134215,
   'codigo_isin': 'BRSTNCLF1RW2'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2031-09-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.1015,
   'taxa_venda': 0.0984,
   'taxa_indicativa': 0.1,
   'intervalo_min_d0': 0.0853,
   'intervalo_max_d0': 0.1157,
   'intervalo_min_d1': 0.0852,
   'intervalo_max_d1': 0.1162,
   'pu': 18114.705364,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCLF1RX0'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2031-12-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.104,
   'taxa_venda': 0.1,
   'taxa_indicativa': 0.101,
   'intervalo_min_d0': 0.0854,
   'intervalo_max_d0': 0.1161,
   'intervalo_min_d1': 0.0855,
   'intervalo_max_d1': 0.1168,
   'pu': 18109.058465,
   'desvio_padrao': 0.00018649453075,
   'codigo_isin': 'BRSTNCLF1RZ5'},
  {'tipo_titulo': 'LTN',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2032-01-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '100000',
   'data_base': '2025-01-10',
   'taxa_compra': 13.8579,
   'taxa_venda': 13.848,
   'taxa_indicativa': 13.8519,
   'intervalo_min_d0': 13.3054,
   'intervalo_max_d0': 14.3116,
   'intervalo_min_d1': 13.3902,
   'intervalo_max_d1': 14.3964,
   'pu': 464.622751,
   'desvio_padrao': 0.00071560317216,
   'codigo_isin': 'BRSTNCLTN8J8'},
  {'tipo_titulo': 'LFT',
   'expressao': 'Rentabilidade (% a.a.)/252',
   'data_vencimento': '2032-03-01',
   'data_referencia': '2026-01-20',
   'codigo_selic': '210100',
   'data_base': '2000-07-01',
   'taxa_compra': 0.106,
   'taxa_venda': 0.105,
   'taxa_indicativa': 0.1055,
   'intervalo_min_d0': 0.0871,
   'intervalo_max_d0': 0.1138,
   'intervalo_min_d1': 0.0865,
   'intervalo_max_d1': 0.1154,
   'pu': 18099.695543,
   'desvio_padrao': 0,
   'codigo_isin': 'BRSTNCLF1S08'},
  {'tipo_titulo': 'NTN-B',
   'expressao': 'Taxa (% a.a.)/252',
   'data_vencimento': '2032-08-15',
   'data_referencia': '2026-01-20',

In [5]:

import pandas as pd 

def api_list_to_df(dados: list) -> pd.DataFrame:
    """
    Converte uma lista de dicionários em um DataFrame.
    """
    registros = [
        item
        for lista_do_dia in dados
        for item in (lista_do_dia or [])
        if isinstance (item, dict)
    ]

    if not registros:
        return pd.DataFrame()
    
    df = pd.DataFrame.from_records(registros)
    
    return df

In [6]:
api_list_to_df(dados)

,tipo_titulo,expressao,data_vencimento,data_referencia,codigo_selic,data_base,taxa_compra,taxa_venda,taxa_indicativa,intervalo_min_d0,intervalo_max_d0,intervalo_min_d1,intervalo_max_d1,pu,desvio_padrao,codigo_isin
0,LFT,Rentabilidade (% a.a.)/252,2026-03-01,2026-01-20,210100,2000-07-01,0.0251,0.0182,0.0213,-0.0503,0.0674,-0.0511,0.0676,18215.384108,0.000802,BRSTNCLF1RE0
1,LTN,Taxa (% a.a.)/252,2026-04-01,2026-01-20,100000,2024-01-05,14.7607,14.7465,14.7572,14.6982,14.9442,14.7120,14.9553,973.590039,0.002249,BRSTNCLTN8B5
2,LTN,Taxa (% a.a.)/252,2026-07-01,2026-01-20,100000,2023-01-06,14.4529,14.4409,14.4474,14.3109,14.6730,14.3299,14.6873,942.796683,0.003314,BRSTNCLTN848
3,NTN-B,Taxa (% a.a.)/252,2026-08-15,2026-01-20,760199,2000-07-15,10.3441,10.3117,10.3300,9.9204,10.7749,9.9403,10.7997,4601.380001,0.000000,BRSTNCNTB4U6
4,LFT,Rentabilidade (% a.a.)/252,2026-09-01,2026-01-20,210100,2000-07-01,-0.0100,-0.0188,-0.0157,-0.0419,0.0572,-0.0419,0.0573,18217.533573,0.000562,BRSTNCLF1RF7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,NTN-B,Taxa (% a.a.)/252,2040-08-15,2026-01-19,760199,2000-07-15,7.5475,7.5168,7.5388,7.3610,7.7045,7.3794,7.7228,4116.364575,0.003264,BRSTNCNTB3C6
100,NTN-B,Taxa (% a.a.)/252,2045-05-15,2026-01-19,760199,2000-07-15,7.4133,7.3843,7.3970,7.2378,7.5676,7.2494,7.5792,4016.292882,0.003656,BRSTNCNTB0A6
101,NTN-B,Taxa (% a.a.)/252,2050-08-15,2026-01-19,760199,2000-07-15,7.3539,7.3222,7.3370,7.1820,7.5044,7.1962,7.5184,4044.707225,0.004286,BRSTNCNTB3D4
102,NTN-B,Taxa (% a.a.)/252,2055-05-15,2026-01-19,760199,2000-07-15,7.3020,7.2688,7.2863,7.1304,7.4514,7.1468,7.4676,3961.202539,0.003527,BRSTNCNTB4Q4
103,NTN-B,Taxa (% a.a.)/252,2060-08-15,2026-01-19,760199,2000-07-15,7.3414,7.3108,7.3247,7.1671,7.4877,7.1857,7.5062,3978.682291,0.004589,BRSTNCNTB690

In [1]:
from titulospub import *

In [2]:
var = VariaveisMercado()

In [3]:
var.atualizar_tudo()

Atualizando variáveis de mercado...
Buscando feriados via scraping...
Calculando IPCA dict...
Buscando CDI...
Realizando scraping ANBIMA...
[OK] Cache salvo para todos os títulos ANBIMA.
Realizando scraping BMF...
[INFO] Encontrados 4 arquivos com prefixo Interest_Rate_SettlementPriceFile_Futures_20260128_
[INFO] Arquivo mais recente selecionado: Interest_Rate_SettlementPriceFile_Futures_20260128_4.csv
[INFO] Data de modificação: Wed Jan 28 18:57:36 2026
[OK] Cache salvo para todos os contrados de DI e DAP.
Realizando scraping VNA_LFT...
[OK] Cache salvo para VNA_LFT.
[OK] Atualização concluída.

In [4]:
(var._anbimas["NTN-B"])

   TITULO       DATA VENCIMENTO   ANBIMA           PU
0   NTN-B 2026-01-28 2026-08-15  10.2832  4617.155828
1   NTN-B 2026-01-28 2027-05-15   8.4700  4520.549373
2   NTN-B 2026-01-28 2028-08-15   7.9331  4525.347327
3   NTN-B 2026-01-28 2029-05-15   7.7619  4433.157745
4   NTN-B 2026-01-28 2030-08-15   7.7039  4439.512164
5   NTN-B 2026-01-28 2031-05-15   7.6576  4343.947945
6   NTN-B 2026-01-28 2032-08-15   7.6493  4352.299598
7   NTN-B 2026-01-28 2033-05-15   7.6400  4255.679370
8   NTN-B 2026-01-28 2035-05-15   7.5309  4211.010191
9   NTN-B 2026-01-28 2037-05-15   7.4999  4158.788252
10  NTN-B 2026-01-28 2040-08-15   7.3933  4181.010354
11  NTN-B 2026-01-28 2045-05-15   7.2204  4101.772951
12  NTN-B 2026-01-28 2050-08-15   7.1435  4145.353982
13  NTN-B 2026-01-28 2055-05-15   7.1022  4062.154250
14  NTN-B 2026-01-28 2060-08-15   7.1330  4085.854764

In [5]:
var._anbimas["NTN-B"].to_excel("ntnb_anbima.xlsx", index=False)
print("Arquivo exportado: ntnb_anbima.xlsx")

Arquivo exportado: ntnb_anbima.xlsx